name: CICD

on:
  push:
    branches: ["master", "development"]
  pull_request:
    branches: ["master", "development"]
jobs:
  # the "build" workflow
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4
    
    - name: Install dependencies
      run: |
        go version
        go get github.com/badoux/checkmail
        go get github.com/jinzhu/gorm
        go get golang.org/x/crypto/bcrypt
        go get github.com/dgrijalva/jwt-go
        go get github.com/gorilla/mux
        go get github.com/jinzhu/gorm/dialects/postgres
        go get github.com/joho/godotenv
        go get gopkg.in/go-playground/assert.v1
    
    - name: Run build
      run: go build .

    # define own testing mechanism
    - name: Run testing
      run: cd test && go test -v